commits.message = "${artifactName} ${nextVersion} (was ${currentVersion})"

pullRequests.grouping = [
  { name = "patches", "title" = "Patch updates", "filter" = [{"version" = "patch"}] }
]

updates.pin = [
  { groupId = "org.scala-lang", artifactId = "scala-library", version = "2.13." }
]
